---
server:
  port: '${SERVER_PORT:8081}'

paymybuddy:
  security:
    allowedOrigins:
      - '${CLIENT_URL:http://localhost:3000}'

spring:
  jpa:
    hibernate:
      ddl-auto: 'validate'
    open-in-view: false
  datasource:
    url: 'jdbc:mariadb://${MYSQL_HOST:localhost}:${MYSQL_PORT:14373}/${MYSQL_DATABASE:pmb}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC'
    username: '${MYSQL_USERNAME:pmb}'
    password: '${MYSQL_PASSWORD:pmb}'
  redis:
    database: '${REDIS_DATABASE:0}'
    host: '${REDIS_HOST:localhost}'
    port: '${REDIS_PORT:14374}'
    password: '${REDIS_PASSWORD:pmb}'

management:
  server:
    address: "${HTTP_MANAGEMENT_ADDR:127.0.0.1}"
    port: "${HTTP_MANAGEMENT_PORT:-1}"

springdoc:
  api-docs:
    enabled: "${API_DOCS_ENABLED:false}"
    path: /api-docs
  swagger-ui:
    enabled: "${SWAGGER_UI_ENABLED:false}"
    path: /docs.html
    operationsSorter: alpha

logging:
  level:
    # Disable useless hibernate warnings
    org.hibernate.engine.jdbc.spi.SqlExceptionHelper: FATAL
    org.hibernate.persister.entity: ERROR
