---
version: '3'
services:
  sqldb:
    image: mariadb:10.5
    ports:
      - '14373:3306'
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_USER: pmb
      MYSQL_PASSWORD: pmb
      MYSQL_DATABASE: pmb
