---
version: '3'
services:
  sqldb:
    image: mariadb:10.5
    ports:
      - '14373:3306'
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_USER: pmb
      MYSQL_PASSWORD: pmb
      MYSQL_DATABASE: pmb
  redisdb:
    image: redis:6.0
    ports:
      - '14374:6379'
    command: redis-server --requirepass pmb
